import { EnumWakfuState } from "./types";

export const WakfuStateLabels: Record<EnumWakfuState, string> = {
  [EnumWakfuState.EtoiEskeutula]: "Etoi Eskeutula",
  [EnumWakfuState.AuraDeLamour]: "Aura de l'Amour",
  [EnumWakfuState.PeaceAndLove]: "Peace and Love",
  [EnumWakfuState.LeDemiPayAime]: "Le Demi Pay Aime",
  [EnumWakfuState.EmblemeIop]: "Emblème du Iop",
  [EnumWakfuState.EmblemeCra]: "Emblème du Cra",
  [EnumWakfuState.EmblemeSacrieur]: "Emblème du Sacrieur",
  [EnumWakfuState.EmblemeEcaflip]: "Emblème d'Ecaflip",
  [EnumWakfuState.EmblemeEniripsa]: "Emblème d'Eniripsa",
  [EnumWakfuState.EmblemeSadida]: "Emblème du Sadida",
  [EnumWakfuState.EmblemeXelor]: "Emblème du Xelor",
  [EnumWakfuState.EmblemeEnutrof]: "Emblème d'Enutrof",
  [EnumWakfuState.EmblemeRoublard]: "Emblème du Roublard",
  [EnumWakfuState.EmblemePandawa]: "Emblème du Pandawa",
  [EnumWakfuState.EmblemeFeca]: "Emblème du Feca",
  [EnumWakfuState.EmblemeOsamodas]: "Emblème d'Osamodas",
  [EnumWakfuState.EmblemeSteamer]: "Emblème du Steamer",
  [EnumWakfuState.EmblemeSram]: "Emblème du Sram",
  [EnumWakfuState.EmblemeZobal]: "Emblème du Zobal",
  [EnumWakfuState.InsigneMerydes]: "Insigne des Merydes",
  [EnumWakfuState.Muraille50]: "Muraille 50%",
  [EnumWakfuState.Muraille75]: "Muraille 75%",
  [EnumWakfuState.Vivacite90]: "Vivacité 90%",
  [EnumWakfuState.Requinquage25]: "Requinquage 25%",
  [EnumWakfuState.Requinquage33]: "Requinquage 33%",
  [EnumWakfuState.Requinquage50]: "Requinquage 50%",
  [EnumWakfuState.Requinquage66]: "Requinquage 66%",
  [EnumWakfuState.Requinquage75]: "Requinquage 75%",
  [EnumWakfuState.TransfertTellurique]: "Transfert Tellurique",
  [EnumWakfuState.Berserk50]: "Berserk 50%",
  [EnumWakfuState.Berserk75]: "Berserk 75%",
  [EnumWakfuState.Rage]: "Rage",
  [EnumWakfuState.Fortification]: "Fortification",
  [EnumWakfuState.PacteAnatharI]: "Pacte d'Anathar I",
  [EnumWakfuState.PacteAnatharII]: "Pacte d'Anathar II",
  [EnumWakfuState.PacteAnatharIII]: "Pacte d'Anathar III",
  [EnumWakfuState.PacteAnatharIV]: "Pacte d'Anathar IV",
  [EnumWakfuState.PacteAnatharV]: "Pacte d'Anathar V",
  [EnumWakfuState.Eternite]: "Éternité",
  [EnumWakfuState.Dofushu]: "Dofushu",
  [EnumWakfuState.DofusIvoire]: "Dofus Ivoire",
  [EnumWakfuState.DofusPrismatique]: "Dofus Prismatique",
  [EnumWakfuState.DofusTurquoise]: "Dofus Turquoise",
};
