import type { JSONSchema } from "json-schema-to-ts";

export const WakfuCollectibleResourceSchema = {
  type: "object",
  properties: {
    id: { type: "number" },
    skillId: { type: "number" },
    resourceId: { type: "number" },
    resourceIndex: { type: "number" },
    collectItemId: { type: "number" },
    resourceNextIndex: { type: "number" },
    skillLevelRequired: { type: "number" },
    simultaneousPlayer: { type: "number" },
    visualFeedbackId: { type: "number" },
    duration: { type: "number" },
    mruOrder: { type: "number" },
    xpFactor: { type: "number" },
    collectLootListId: { type: "number" },
    collectConsumableItemId: { type: "number" },
    collectGfxId: { type: "number" },
    displayInCraftDialog: { type: "boolean" },
  },
  required: [
    "id",
    "skillId",
    "resourceId",
    "resourceIndex",
    "collectItemId",
    "resourceNextIndex",
    "skillLevelRequired",
    "simultaneousPlayer",
    "visualFeedbackId",
    "duration",
    "mruOrder",
    "xpFactor",
    "collectLootListId",
    "collectConsumableItemId",
    "collectGfxId",
    "displayInCraftDialog",
  ],
} as const satisfies JSONSchema;
